(script static "void" x70_finale
    (cinematic_suppress_bsp_object_creation true )
    (player_effect_start 1 0 )
    (player_effect_set_max_translation 0 0 0 )
    (player_effect_set_max_rotation 0 0 0 )
    (player_effect_set_max_rumble 0 0 )
    (sound_looping_start "sound\sinomatixx_music\x70_music" none 1 )
    (sound_looping_start "sound\sinomatixx_foley\x70_foley1" none 1 )
    (object_destroy_containing "nipple" )
    (fade_out 1 1 1 50 )
    (sleep 30 )
    (cinematic_start )
    (camera_control true )
    (switch_bsp 7 )
    (object_teleport (player0 )player0_finale_pause )
    (object_teleport (player1 )player1_finale_pause )
    (object_teleport (player2 )player2_finale_pause )
    (object_teleport (player3 )player3_finale_pause )
    (object_teleport (player4 )player4_finale_pause )
    (object_teleport (player5 )player5_finale_pause )
    (object_teleport (player6 )player6_finale_pause )
    (object_teleport (player7 )player7_finale_pause )
    (object_teleport (player8 )player8_finale_pause )
    (object_teleport (player9 )player9_finale_pause )
    (object_teleport (player10 )player10_finale_pause )
    (object_teleport (player11 )player11_finale_pause )
    (object_teleport (player12 )player12_finale_pause )
    (object_teleport (player13 )player13_finale_pause )
    (object_teleport (player14 )player14_finale_pause )
    (object_teleport (player15 )player15_finale_pause )

    (unit_suspended (player0 )true )
    (unit_suspended (player1 )true )
    (unit_suspended (player2 )true )
    (unit_suspended (player3 )true )
    (unit_suspended (player4 )true )
    (unit_suspended (player5 )true )
    (unit_suspended (player6 )true )
    (unit_suspended (player7 )true )
    (unit_suspended (player8 )true )
    (unit_suspended (player9 )true )
    (unit_suspended (player10 )true )
    (unit_suspended (player11 )true )
    (unit_suspended (player12 )true )
    (unit_suspended (player13 )true )
    (unit_suspended (player14 )true )
    (unit_suspended (player15 )true )

    (hangar_1 )
    (hangar_2 )
    (sound_class_set_gain "weapon_fire" 0 0 )
    (sound_class_set_gain "projectile_detonation" 0 0 )
    (sound_class_set_gain "projectile_impact" 0 0 )
    (sound_class_set_gain "unit_dialog" 0 0 )
    (hangar_3 )
    (if (= easy (game_difficulty_get_real ))
        (begin (switch_bsp 8 )
        (launch_1 )
        (sound_class_set_gain "unit_footsteps" 0 0 )
        (launch_2 )
        (fade_out 0 0 0 0 )
        (switch_bsp 9 )
        (fade_in 0 0 0 0 )
        (rasterizer_model_ambient_reflection_tint 1 1 1 1 )
        (int_1 )
        (space_1 )
        (fade_in 1 1 1 15 )
        (int_2 )
        (space_2 )
        (int_3 )
        (space_3 )
        (int_4 )
        (fade_out 0 0 0 120 )
        (sleep 520 )
        (cinematic_screen_effect_stop )
        (rasterizer_model_ambient_reflection_tint 0 0 0 0 )(print "cue credits" ))
    )
    (if (= normal (game_difficulty_get_real ))(begin (switch_bsp 8 )
    (launch_1 )
    (sound_class_set_gain "unit_footsteps" 0 0 )
    (launch_2 )
    (fade_out 0 0 0 0 )
    (switch_bsp 9 )
    (fade_in 0 0 0 0 )
    (rasterizer_model_ambient_reflection_tint 1 1 1 1 )
    (int_1 )
    (space_1 )
    (fade_in 1 1 1 15 )
    (int_2 )
    (space_2 )
    (int_3 )
    (space_3 )
    (int_4 )
    (fade_out 0 0 0 120 )
    (sleep 520 )
    (cinematic_screen_effect_stop )
    (rasterizer_model_ambient_reflection_tint 0 0 0 0 )(print "cue credits" )))
    (if (= hard (game_difficulty_get_real ))(begin (switch_bsp 8 )
    (launch_1 )
    (sound_class_set_gain "unit_footsteps" 0 0 )
    (launch_2 )
    (fade_out 0 0 0 0 )
    (switch_bsp 9 )
    (fade_in 0 0 0 0 )
    (rasterizer_model_ambient_reflection_tint 1 1 1 1 )
    (int_1 )
    (space_1 )
    (fade_in 1 1 1 15 )
    (int_2 )
    (space_2 )
    (int_3 )
    (space_3 )
    (int_4 )
    (fade_out 0 0 0 120 )
    (sleep 520 )
    (cinematic_screen_effect_stop )
    (rasterizer_model_ambient_reflection_tint 0 0 0 0 )(print "cue credits" )))(if (= impossible (game_difficulty_get_real ))(begin (print "happy easter" )
    (switch_bsp 8 )
    (happy_easter )
    (switch_bsp 9 )
    (fade_in 0 0 0 0 )
    (rasterizer_model_ambient_reflection_tint 1 1 1 1 )
    (int_1 )
    (space_1 )
    (fade_in 1 1 1 15 )
    (int_2 )
    (space_2 )
    (int_3 )
    (space_3 )
    (int_4 )
    (fade_out 0 0 0 120 )
    (sleep 520 )
    (cinematic_screen_effect_stop )
    (rasterizer_model_ambient_reflection_tint 0 0 0 0 )(print "cue credits" )))
)