version: 1
user: gravemind
cloudpath: CoopEvolved
engine: gbx-custom
tagsize: 64M
extendlimits: true
scenarios:
  - levels/a50/a50_coop_evolved_dev
  - levels/b30/b30_coop_evolved_dev
  - levels/c10/c10_coop_evolved_dev
  - levels/c20/c20_coop_evolved_dev
  - levels/d40/d40_coop_evolved_dev
outputpath: package/game-maps
packagelabel: coopevolved
postbuild:
  - echo Building mercury package...
  - mercury pack "$PROJECT_PATH/package/" $MERCURY_ARCHIVE/
  - mercury packdiff $MERCURY_ARCHIVE/$(ls -1 $MERCURY_ARCHIVE | grep $MERCURY_PACKAGE | tail -2 | head -n 1) $MERCURY_ARCHIVE/$(ls $MERCURY_ARCHIVE | grep $MERCURY_PACKAGE | tail -1) $MERCURY_ARCHIVE/updates/
