---@class EngineTagDataShaderTransparentGenericStageInputColorEnum : Enum 

---@class EngineTagDataShaderTransparentGenericStageInputColorZero : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorOne : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorOneHalf : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorNegativeOne : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorNegativeOneHalf : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorMapColor0 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorMapColor1 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorMapColor2 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorMapColor3 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorVertexColor0DiffuseLight : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorVertexColor1FadePerpendicular : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorScratchColor0 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorScratchColor1 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorConstantColor0 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorConstantColor1 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorMapAlpha0 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorMapAlpha1 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorMapAlpha2 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorMapAlpha3 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorVertexAlpha0FadeNone : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorVertexAlpha1FadePerpendicular : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorScratchAlpha0 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorScratchAlpha1 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorConstantAlpha0 : EngineTagDataShaderTransparentGenericStageInputColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputColorConstantAlpha1 : EngineTagDataShaderTransparentGenericStageInputColorEnum 

---@alias EngineTagDataShaderTransparentGenericStageInputColor 
---| EngineTagDataShaderTransparentGenericStageInputColorZero
---| EngineTagDataShaderTransparentGenericStageInputColorOne
---| EngineTagDataShaderTransparentGenericStageInputColorOneHalf
---| EngineTagDataShaderTransparentGenericStageInputColorNegativeOne
---| EngineTagDataShaderTransparentGenericStageInputColorNegativeOneHalf
---| EngineTagDataShaderTransparentGenericStageInputColorMapColor0
---| EngineTagDataShaderTransparentGenericStageInputColorMapColor1
---| EngineTagDataShaderTransparentGenericStageInputColorMapColor2
---| EngineTagDataShaderTransparentGenericStageInputColorMapColor3
---| EngineTagDataShaderTransparentGenericStageInputColorVertexColor0DiffuseLight
---| EngineTagDataShaderTransparentGenericStageInputColorVertexColor1FadePerpendicular
---| EngineTagDataShaderTransparentGenericStageInputColorScratchColor0
---| EngineTagDataShaderTransparentGenericStageInputColorScratchColor1
---| EngineTagDataShaderTransparentGenericStageInputColorConstantColor0
---| EngineTagDataShaderTransparentGenericStageInputColorConstantColor1
---| EngineTagDataShaderTransparentGenericStageInputColorMapAlpha0
---| EngineTagDataShaderTransparentGenericStageInputColorMapAlpha1
---| EngineTagDataShaderTransparentGenericStageInputColorMapAlpha2
---| EngineTagDataShaderTransparentGenericStageInputColorMapAlpha3
---| EngineTagDataShaderTransparentGenericStageInputColorVertexAlpha0FadeNone
---| EngineTagDataShaderTransparentGenericStageInputColorVertexAlpha1FadePerpendicular
---| EngineTagDataShaderTransparentGenericStageInputColorScratchAlpha0
---| EngineTagDataShaderTransparentGenericStageInputColorScratchAlpha1
---| EngineTagDataShaderTransparentGenericStageInputColorConstantAlpha0
---| EngineTagDataShaderTransparentGenericStageInputColorConstantAlpha1

---@class EngineTagDataShaderTransparentGenericStageInputColorTable 
---@field olorZero EngineTagDataShaderTransparentGenericStageInputColorZero
---@field olorOne EngineTagDataShaderTransparentGenericStageInputColorOne
---@field olorOneHalf EngineTagDataShaderTransparentGenericStageInputColorOneHalf
---@field olorNegativeOne EngineTagDataShaderTransparentGenericStageInputColorNegativeOne
---@field olorNegativeOneHalf EngineTagDataShaderTransparentGenericStageInputColorNegativeOneHalf
---@field olorMapColor0 EngineTagDataShaderTransparentGenericStageInputColorMapColor0
---@field olorMapColor1 EngineTagDataShaderTransparentGenericStageInputColorMapColor1
---@field olorMapColor2 EngineTagDataShaderTransparentGenericStageInputColorMapColor2
---@field olorMapColor3 EngineTagDataShaderTransparentGenericStageInputColorMapColor3
---@field olorVertexColor0DiffuseLight EngineTagDataShaderTransparentGenericStageInputColorVertexColor0DiffuseLight
---@field olorVertexColor1FadePerpendicular EngineTagDataShaderTransparentGenericStageInputColorVertexColor1FadePerpendicular
---@field olorScratchColor0 EngineTagDataShaderTransparentGenericStageInputColorScratchColor0
---@field olorScratchColor1 EngineTagDataShaderTransparentGenericStageInputColorScratchColor1
---@field olorConstantColor0 EngineTagDataShaderTransparentGenericStageInputColorConstantColor0
---@field olorConstantColor1 EngineTagDataShaderTransparentGenericStageInputColorConstantColor1
---@field olorMapAlpha0 EngineTagDataShaderTransparentGenericStageInputColorMapAlpha0
---@field olorMapAlpha1 EngineTagDataShaderTransparentGenericStageInputColorMapAlpha1
---@field olorMapAlpha2 EngineTagDataShaderTransparentGenericStageInputColorMapAlpha2
---@field olorMapAlpha3 EngineTagDataShaderTransparentGenericStageInputColorMapAlpha3
---@field olorVertexAlpha0FadeNone EngineTagDataShaderTransparentGenericStageInputColorVertexAlpha0FadeNone
---@field olorVertexAlpha1FadePerpendicular EngineTagDataShaderTransparentGenericStageInputColorVertexAlpha1FadePerpendicular
---@field olorScratchAlpha0 EngineTagDataShaderTransparentGenericStageInputColorScratchAlpha0
---@field olorScratchAlpha1 EngineTagDataShaderTransparentGenericStageInputColorScratchAlpha1
---@field olorConstantAlpha0 EngineTagDataShaderTransparentGenericStageInputColorConstantAlpha0
---@field olorConstantAlpha1 EngineTagDataShaderTransparentGenericStageInputColorConstantAlpha1
Engine.tag.shaderTransparentGenericStageInputColor = {} 

---@class EngineTagDataShaderTransparentGenericStageInputAlphaEnum : Enum 

---@class EngineTagDataShaderTransparentGenericStageInputAlphaZero : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaOne : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaOneHalf : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaNegativeOne : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaNegativeOneHalf : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha0 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha1 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha2 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha3 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaVertexAlpha0FadeNone : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaVertexAlpha1FadePerpendicular : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaScratchAlpha0 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaScratchAlpha1 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaConstantAlpha0 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaConstantAlpha1 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue0 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue1 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue2 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue3 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaVertexBlue0BlueLight : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaVertexBlue1FadeParallel : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaScratchBlue0 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaScratchBlue1 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaConstantBlue0 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 
---@class EngineTagDataShaderTransparentGenericStageInputAlphaConstantBlue1 : EngineTagDataShaderTransparentGenericStageInputAlphaEnum 

---@alias EngineTagDataShaderTransparentGenericStageInputAlpha 
---| EngineTagDataShaderTransparentGenericStageInputAlphaZero
---| EngineTagDataShaderTransparentGenericStageInputAlphaOne
---| EngineTagDataShaderTransparentGenericStageInputAlphaOneHalf
---| EngineTagDataShaderTransparentGenericStageInputAlphaNegativeOne
---| EngineTagDataShaderTransparentGenericStageInputAlphaNegativeOneHalf
---| EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha0
---| EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha1
---| EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha2
---| EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha3
---| EngineTagDataShaderTransparentGenericStageInputAlphaVertexAlpha0FadeNone
---| EngineTagDataShaderTransparentGenericStageInputAlphaVertexAlpha1FadePerpendicular
---| EngineTagDataShaderTransparentGenericStageInputAlphaScratchAlpha0
---| EngineTagDataShaderTransparentGenericStageInputAlphaScratchAlpha1
---| EngineTagDataShaderTransparentGenericStageInputAlphaConstantAlpha0
---| EngineTagDataShaderTransparentGenericStageInputAlphaConstantAlpha1
---| EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue0
---| EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue1
---| EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue2
---| EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue3
---| EngineTagDataShaderTransparentGenericStageInputAlphaVertexBlue0BlueLight
---| EngineTagDataShaderTransparentGenericStageInputAlphaVertexBlue1FadeParallel
---| EngineTagDataShaderTransparentGenericStageInputAlphaScratchBlue0
---| EngineTagDataShaderTransparentGenericStageInputAlphaScratchBlue1
---| EngineTagDataShaderTransparentGenericStageInputAlphaConstantBlue0
---| EngineTagDataShaderTransparentGenericStageInputAlphaConstantBlue1

---@class EngineTagDataShaderTransparentGenericStageInputAlphaTable 
---@field lphaZero EngineTagDataShaderTransparentGenericStageInputAlphaZero
---@field lphaOne EngineTagDataShaderTransparentGenericStageInputAlphaOne
---@field lphaOneHalf EngineTagDataShaderTransparentGenericStageInputAlphaOneHalf
---@field lphaNegativeOne EngineTagDataShaderTransparentGenericStageInputAlphaNegativeOne
---@field lphaNegativeOneHalf EngineTagDataShaderTransparentGenericStageInputAlphaNegativeOneHalf
---@field lphaMapAlpha0 EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha0
---@field lphaMapAlpha1 EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha1
---@field lphaMapAlpha2 EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha2
---@field lphaMapAlpha3 EngineTagDataShaderTransparentGenericStageInputAlphaMapAlpha3
---@field lphaVertexAlpha0FadeNone EngineTagDataShaderTransparentGenericStageInputAlphaVertexAlpha0FadeNone
---@field lphaVertexAlpha1FadePerpendicular EngineTagDataShaderTransparentGenericStageInputAlphaVertexAlpha1FadePerpendicular
---@field lphaScratchAlpha0 EngineTagDataShaderTransparentGenericStageInputAlphaScratchAlpha0
---@field lphaScratchAlpha1 EngineTagDataShaderTransparentGenericStageInputAlphaScratchAlpha1
---@field lphaConstantAlpha0 EngineTagDataShaderTransparentGenericStageInputAlphaConstantAlpha0
---@field lphaConstantAlpha1 EngineTagDataShaderTransparentGenericStageInputAlphaConstantAlpha1
---@field lphaMapBlue0 EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue0
---@field lphaMapBlue1 EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue1
---@field lphaMapBlue2 EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue2
---@field lphaMapBlue3 EngineTagDataShaderTransparentGenericStageInputAlphaMapBlue3
---@field lphaVertexBlue0BlueLight EngineTagDataShaderTransparentGenericStageInputAlphaVertexBlue0BlueLight
---@field lphaVertexBlue1FadeParallel EngineTagDataShaderTransparentGenericStageInputAlphaVertexBlue1FadeParallel
---@field lphaScratchBlue0 EngineTagDataShaderTransparentGenericStageInputAlphaScratchBlue0
---@field lphaScratchBlue1 EngineTagDataShaderTransparentGenericStageInputAlphaScratchBlue1
---@field lphaConstantBlue0 EngineTagDataShaderTransparentGenericStageInputAlphaConstantBlue0
---@field lphaConstantBlue1 EngineTagDataShaderTransparentGenericStageInputAlphaConstantBlue1
Engine.tag.shaderTransparentGenericStageInputAlpha = {} 

---@class EngineTagDataShaderTransparentGenericStageInputMappingColorEnum : Enum 

---@class EngineTagDataShaderTransparentGenericStageInputMappingColorClampX : EngineTagDataShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputMappingColor1ClampX : EngineTagDataShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputMappingColor2 : EngineTagDataShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputMappingColor12 : EngineTagDataShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputMappingColorClampX12 : EngineTagDataShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputMappingColor12ClampX : EngineTagDataShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputMappingColorX : EngineTagDataShaderTransparentGenericStageInputMappingColorEnum 
---@class EngineTagDataShaderTransparentGenericStageInputMappingColorX1 : EngineTagDataShaderTransparentGenericStageInputMappingColorEnum 

---@alias EngineTagDataShaderTransparentGenericStageInputMappingColor 
---| EngineTagDataShaderTransparentGenericStageInputMappingColorClampX
---| EngineTagDataShaderTransparentGenericStageInputMappingColor1ClampX
---| EngineTagDataShaderTransparentGenericStageInputMappingColor2
---| EngineTagDataShaderTransparentGenericStageInputMappingColor12
---| EngineTagDataShaderTransparentGenericStageInputMappingColorClampX12
---| EngineTagDataShaderTransparentGenericStageInputMappingColor12ClampX
---| EngineTagDataShaderTransparentGenericStageInputMappingColorX
---| EngineTagDataShaderTransparentGenericStageInputMappingColorX1

---@class EngineTagDataShaderTransparentGenericStageInputMappingColorTable 
---@field colorClampX EngineTagDataShaderTransparentGenericStageInputMappingColorClampX
---@field color1ClampX EngineTagDataShaderTransparentGenericStageInputMappingColor1ClampX
---@field color2 EngineTagDataShaderTransparentGenericStageInputMappingColor2
---@field color12 EngineTagDataShaderTransparentGenericStageInputMappingColor12
---@field colorClampX12 EngineTagDataShaderTransparentGenericStageInputMappingColorClampX12
---@field color12ClampX EngineTagDataShaderTransparentGenericStageInputMappingColor12ClampX
---@field colorX EngineTagDataShaderTransparentGenericStageInputMappingColorX
---@field colorX1 EngineTagDataShaderTransparentGenericStageInputMappingColorX1
Engine.tag.shaderTransparentGenericStageInputMappingColor = {} 

---@class EngineTagDataShaderTransparentGenericStageOutputFunctionEnum : Enum 

---@class EngineTagDataShaderTransparentGenericStageOutputFunctionMultiply : EngineTagDataShaderTransparentGenericStageOutputFunctionEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputFunctionDotProduct : EngineTagDataShaderTransparentGenericStageOutputFunctionEnum 

---@alias EngineTagDataShaderTransparentGenericStageOutputFunction 
---| EngineTagDataShaderTransparentGenericStageOutputFunctionMultiply
---| EngineTagDataShaderTransparentGenericStageOutputFunctionDotProduct

---@class EngineTagDataShaderTransparentGenericStageOutputFunctionTable 
---@field tionMultiply EngineTagDataShaderTransparentGenericStageOutputFunctionMultiply
---@field tionDotProduct EngineTagDataShaderTransparentGenericStageOutputFunctionDotProduct
Engine.tag.shaderTransparentGenericStageOutputFunction = {} 

---@class EngineTagDataShaderTransparentGenericStageOutputMappingEnum : Enum 

---@class EngineTagDataShaderTransparentGenericStageOutputMappingColorIdentity : EngineTagDataShaderTransparentGenericStageOutputMappingEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy12 : EngineTagDataShaderTransparentGenericStageOutputMappingEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy2 : EngineTagDataShaderTransparentGenericStageOutputMappingEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy4 : EngineTagDataShaderTransparentGenericStageOutputMappingEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputMappingColorBiasBy12 : EngineTagDataShaderTransparentGenericStageOutputMappingEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputMappingColorExpandNormal : EngineTagDataShaderTransparentGenericStageOutputMappingEnum 

---@alias EngineTagDataShaderTransparentGenericStageOutputMapping 
---| EngineTagDataShaderTransparentGenericStageOutputMappingColorIdentity
---| EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy12
---| EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy2
---| EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy4
---| EngineTagDataShaderTransparentGenericStageOutputMappingColorBiasBy12
---| EngineTagDataShaderTransparentGenericStageOutputMappingColorExpandNormal

---@class EngineTagDataShaderTransparentGenericStageOutputMappingTable 
---@field pingColorIdentity EngineTagDataShaderTransparentGenericStageOutputMappingColorIdentity
---@field pingColorScaleBy12 EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy12
---@field pingColorScaleBy2 EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy2
---@field pingColorScaleBy4 EngineTagDataShaderTransparentGenericStageOutputMappingColorScaleBy4
---@field pingColorBiasBy12 EngineTagDataShaderTransparentGenericStageOutputMappingColorBiasBy12
---@field pingColorExpandNormal EngineTagDataShaderTransparentGenericStageOutputMappingColorExpandNormal
Engine.tag.shaderTransparentGenericStageOutputMapping = {} 

---@class EngineTagDataShaderTransparentGenericStageOutputEnum : Enum 

---@class EngineTagDataShaderTransparentGenericStageOutputAlphaDiscard : EngineTagDataShaderTransparentGenericStageOutputEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputAlphaScratchAlpha0FinalAlpha : EngineTagDataShaderTransparentGenericStageOutputEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputAlphaScratchAlpha1 : EngineTagDataShaderTransparentGenericStageOutputEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputAlphaVertexAlpha0Fog : EngineTagDataShaderTransparentGenericStageOutputEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputAlphaVertexAlpha1 : EngineTagDataShaderTransparentGenericStageOutputEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha0 : EngineTagDataShaderTransparentGenericStageOutputEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha1 : EngineTagDataShaderTransparentGenericStageOutputEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha2 : EngineTagDataShaderTransparentGenericStageOutputEnum 
---@class EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha3 : EngineTagDataShaderTransparentGenericStageOutputEnum 

---@alias EngineTagDataShaderTransparentGenericStageOutput 
---| EngineTagDataShaderTransparentGenericStageOutputAlphaDiscard
---| EngineTagDataShaderTransparentGenericStageOutputAlphaScratchAlpha0FinalAlpha
---| EngineTagDataShaderTransparentGenericStageOutputAlphaScratchAlpha1
---| EngineTagDataShaderTransparentGenericStageOutputAlphaVertexAlpha0Fog
---| EngineTagDataShaderTransparentGenericStageOutputAlphaVertexAlpha1
---| EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha0
---| EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha1
---| EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha2
---| EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha3

---@class EngineTagDataShaderTransparentGenericStageOutputTable 
---@field putAlphaDiscard EngineTagDataShaderTransparentGenericStageOutputAlphaDiscard
---@field putAlphaScratchAlpha0FinalAlpha EngineTagDataShaderTransparentGenericStageOutputAlphaScratchAlpha0FinalAlpha
---@field putAlphaScratchAlpha1 EngineTagDataShaderTransparentGenericStageOutputAlphaScratchAlpha1
---@field putAlphaVertexAlpha0Fog EngineTagDataShaderTransparentGenericStageOutputAlphaVertexAlpha0Fog
---@field putAlphaVertexAlpha1 EngineTagDataShaderTransparentGenericStageOutputAlphaVertexAlpha1
---@field putAlphaMapAlpha0 EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha0
---@field putAlphaMapAlpha1 EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha1
---@field putAlphaMapAlpha2 EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha2
---@field putAlphaMapAlpha3 EngineTagDataShaderTransparentGenericStageOutputAlphaMapAlpha3
Engine.tag.shaderTransparentGenericStageOutput = {} 

---@class MetaEngineTagDataShaderTransparentGenericMapFlag 
---@field unfiltered boolean 
---@field uClamped boolean 
---@field vClamped boolean 

---@class MetaEngineTagDataShaderTransparentGenericStageFlags 
---@field colorMux boolean 
---@field alphaMux boolean 
---@field aOutControlsColor0Animation boolean 

---@class MetaEngineTagDataShaderTransparentGenericFlags 
---@field alphaTested boolean 
---@field decal boolean 
---@field twoSided boolean 
---@field firstMapIsInScreenspace boolean 
---@field drawBeforeWater boolean 
---@field ignoreEffect boolean 
---@field scaleFirstMapWithDistance boolean 
---@field numeric boolean 

---@class MetaEngineTagDataShaderTransparentGenericMap 
---@field flags MetaEngineTagDataShaderTransparentGenericMapFlag 
---@field mapUScale number 
---@field mapVScale number 
---@field mapUOffset number 
---@field mapVOffset number 
---@field mapRotation number 
---@field mapmapBias MetaEngineFraction 
---@field map MetaEngineTagDependency 
---@field uAnimationSource EngineTagDataFunctionOut 
---@field uAnimationFunction EngineTagDataWaveFunction 
---@field uAnimationPeriod number 
---@field uAnimationPhase number 
---@field uAnimationScale number 
---@field vAnimationSource EngineTagDataFunctionOut 
---@field vAnimationFunction EngineTagDataWaveFunction 
---@field vAnimationPeriod number 
---@field vAnimationPhase number 
---@field vAnimationScale number 
---@field rotationAnimationSource EngineTagDataFunctionOut 
---@field rotationAnimationFunction EngineTagDataWaveFunction 
---@field rotationAnimationPeriod number 
---@field rotationAnimationPhase number 
---@field rotationAnimationScale number 
---@field rotationAnimationCenter MetaEnginePoint2D 

---@class MetaEngineTagDataShaderTransparentGenericStage 
---@field flags MetaEngineTagDataShaderTransparentGenericStageFlags 
---@field color0Source EngineTagDataFunctionNameNullable 
---@field color0AnimationFunction EngineTagDataWaveFunction 
---@field color0AnimationPeriod number 
---@field color0AnimationLowerBound MetaEngineColorARGB 
---@field color0AnimationUpperBound MetaEngineColorARGB 
---@field color1 MetaEngineColorARGB 
---@field inputA EngineTagDataShaderTransparentGenericStageInputColor 
---@field inputAMapping EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputB EngineTagDataShaderTransparentGenericStageInputColor 
---@field inputBMapping EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputC EngineTagDataShaderTransparentGenericStageInputColor 
---@field inputCMapping EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputD EngineTagDataShaderTransparentGenericStageInputColor 
---@field inputDMapping EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field outputAb EngineTagDataShaderTransparentGenericStageOutput 
---@field outputAbFunction EngineTagDataShaderTransparentGenericStageOutputFunction 
---@field outputBc EngineTagDataShaderTransparentGenericStageOutput 
---@field outputCdFunction EngineTagDataShaderTransparentGenericStageOutputFunction 
---@field outputAbCdMuxSum EngineTagDataShaderTransparentGenericStageOutput 
---@field outputMappingColor EngineTagDataShaderTransparentGenericStageOutputMapping 
---@field inputAAlpha EngineTagDataShaderTransparentGenericStageInputAlpha 
---@field inputAMappingAlpha EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputBAlpha EngineTagDataShaderTransparentGenericStageInputAlpha 
---@field inputBMappingAlpha EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputCAlpha EngineTagDataShaderTransparentGenericStageInputAlpha 
---@field inputCMappingAlpha EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field inputDAlpha EngineTagDataShaderTransparentGenericStageInputAlpha 
---@field inputDMappingAlpha EngineTagDataShaderTransparentGenericStageInputMappingColor 
---@field outputAbAlpha EngineTagDataShaderTransparentGenericStageOutput 
---@field outputCdAlpha EngineTagDataShaderTransparentGenericStageOutput 
---@field outputAbCdMuxSumAlpha EngineTagDataShaderTransparentGenericStageOutput 
---@field outputMappingAlpha EngineTagDataShaderTransparentGenericStageOutputMapping 

---@class MetaEngineTagDataShaderTransparentGeneric: MetaEngineTagDataShader  
---@field numericCounterLimit integer 
---@field shaderTransparentGenericFlags MetaEngineTagDataShaderTransparentGenericFlags 
---@field firstMapType EngineTagDataShaderFirstMapType 
---@field framebufferBlendFunction EngineTagDataFramebufferBlendFunction 
---@field framebufferFadeMode EngineTagDataFramebufferFadeMode 
---@field framebufferFadeSource EngineTagDataFunctionOut 
---@field lensFlareSpacing number 
---@field lensFlare MetaEngineTagDependency 
---@field extraLayers TagBlock<MetaEngineTagDataShaderTransparentExtraLayer> 
---@field maps TagBlock<MetaEngineTagDataShaderTransparentGenericMap> 
---@field stages TagBlock<MetaEngineTagDataShaderTransparentGenericStage> 


