---@class EngineTagDataActorTypeEnum : Enum 

---@class EngineTagDataActorTypeElite : EngineTagDataActorTypeEnum 
---@class EngineTagDataActorTypeJackal : EngineTagDataActorTypeEnum 
---@class EngineTagDataActorTypeGrunt : EngineTagDataActorTypeEnum 
---@class EngineTagDataActorTypeHunter : EngineTagDataActorTypeEnum 
---@class EngineTagDataActorTypeEngineer : EngineTagDataActorTypeEnum 
---@class EngineTagDataActorTypeAssassin : EngineTagDataActorTypeEnum 
---@class EngineTagDataActorTypePlayer : EngineTagDataActorTypeEnum 
---@class EngineTagDataActorTypeMarine : EngineTagDataActorTypeEnum 
---@class EngineTagDataActorTypeCrew : EngineTagDataActorTypeEnum 
---@class EngineTagDataActorTypeCombatForm : EngineTagDataActorTypeEnum 
---@class EngineTagDataActorTypeInfectionForm : EngineTagDataActorTypeEnum 
---@class EngineTagDataActorTypeCarrierForm : EngineTagDataActorTypeEnum 
---@class EngineTagDataActorTypeMonitor : EngineTagDataActorTypeEnum 
---@class EngineTagDataActorTypeSentinel : EngineTagDataActorTypeEnum 
---@class EngineTagDataActorTypeNone : EngineTagDataActorTypeEnum 
---@class EngineTagDataActorTypeMountedWeapon : EngineTagDataActorTypeEnum 

---@alias EngineTagDataActorType 
---| EngineTagDataActorTypeElite
---| EngineTagDataActorTypeJackal
---| EngineTagDataActorTypeGrunt
---| EngineTagDataActorTypeHunter
---| EngineTagDataActorTypeEngineer
---| EngineTagDataActorTypeAssassin
---| EngineTagDataActorTypePlayer
---| EngineTagDataActorTypeMarine
---| EngineTagDataActorTypeCrew
---| EngineTagDataActorTypeCombatForm
---| EngineTagDataActorTypeInfectionForm
---| EngineTagDataActorTypeCarrierForm
---| EngineTagDataActorTypeMonitor
---| EngineTagDataActorTypeSentinel
---| EngineTagDataActorTypeNone
---| EngineTagDataActorTypeMountedWeapon

---@class EngineTagDataActorTypeTable 
---@field elite EngineTagDataActorTypeElite
---@field jackal EngineTagDataActorTypeJackal
---@field grunt EngineTagDataActorTypeGrunt
---@field hunter EngineTagDataActorTypeHunter
---@field engineer EngineTagDataActorTypeEngineer
---@field assassin EngineTagDataActorTypeAssassin
---@field player EngineTagDataActorTypePlayer
---@field marine EngineTagDataActorTypeMarine
---@field crew EngineTagDataActorTypeCrew
---@field combatForm EngineTagDataActorTypeCombatForm
---@field infectionForm EngineTagDataActorTypeInfectionForm
---@field carrierForm EngineTagDataActorTypeCarrierForm
---@field monitor EngineTagDataActorTypeMonitor
---@field sentinel EngineTagDataActorTypeSentinel
---@field none EngineTagDataActorTypeNone
---@field mountedWeapon EngineTagDataActorTypeMountedWeapon
Engine.tag.actorType = {} 

---@class EngineTagDataActorUnreachableDangerTriggerEnum : Enum 

---@class EngineTagDataActorUnreachableDangerTriggerNever : EngineTagDataActorUnreachableDangerTriggerEnum 
---@class EngineTagDataActorUnreachableDangerTriggerVisible : EngineTagDataActorUnreachableDangerTriggerEnum 
---@class EngineTagDataActorUnreachableDangerTriggerShooting : EngineTagDataActorUnreachableDangerTriggerEnum 
---@class EngineTagDataActorUnreachableDangerTriggerShootingNearUs : EngineTagDataActorUnreachableDangerTriggerEnum 
---@class EngineTagDataActorUnreachableDangerTriggerDamagingUs : EngineTagDataActorUnreachableDangerTriggerEnum 
---@class EngineTagDataActorUnreachableDangerTriggerUnused : EngineTagDataActorUnreachableDangerTriggerEnum 
---@class EngineTagDataActorUnreachableDangerTriggerUnused1 : EngineTagDataActorUnreachableDangerTriggerEnum 
---@class EngineTagDataActorUnreachableDangerTriggerUnused2 : EngineTagDataActorUnreachableDangerTriggerEnum 
---@class EngineTagDataActorUnreachableDangerTriggerUnused3 : EngineTagDataActorUnreachableDangerTriggerEnum 
---@class EngineTagDataActorUnreachableDangerTriggerUnused4 : EngineTagDataActorUnreachableDangerTriggerEnum 

---@alias EngineTagDataActorUnreachableDangerTrigger 
---| EngineTagDataActorUnreachableDangerTriggerNever
---| EngineTagDataActorUnreachableDangerTriggerVisible
---| EngineTagDataActorUnreachableDangerTriggerShooting
---| EngineTagDataActorUnreachableDangerTriggerShootingNearUs
---| EngineTagDataActorUnreachableDangerTriggerDamagingUs
---| EngineTagDataActorUnreachableDangerTriggerUnused
---| EngineTagDataActorUnreachableDangerTriggerUnused1
---| EngineTagDataActorUnreachableDangerTriggerUnused2
---| EngineTagDataActorUnreachableDangerTriggerUnused3
---| EngineTagDataActorUnreachableDangerTriggerUnused4

---@class EngineTagDataActorUnreachableDangerTriggerTable 
---@field erNever EngineTagDataActorUnreachableDangerTriggerNever
---@field erVisible EngineTagDataActorUnreachableDangerTriggerVisible
---@field erShooting EngineTagDataActorUnreachableDangerTriggerShooting
---@field erShootingNearUs EngineTagDataActorUnreachableDangerTriggerShootingNearUs
---@field erDamagingUs EngineTagDataActorUnreachableDangerTriggerDamagingUs
---@field erUnused EngineTagDataActorUnreachableDangerTriggerUnused
---@field erUnused1 EngineTagDataActorUnreachableDangerTriggerUnused1
---@field erUnused2 EngineTagDataActorUnreachableDangerTriggerUnused2
---@field erUnused3 EngineTagDataActorUnreachableDangerTriggerUnused3
---@field erUnused4 EngineTagDataActorUnreachableDangerTriggerUnused4
Engine.tag.actorUnreachableDangerTrigger = {} 

---@class EngineTagDataActorDefensiveCrouchTypeEnum : Enum 

---@class EngineTagDataActorDefensiveCrouchTypeNever : EngineTagDataActorDefensiveCrouchTypeEnum 
---@class EngineTagDataActorDefensiveCrouchTypeDanger : EngineTagDataActorDefensiveCrouchTypeEnum 
---@class EngineTagDataActorDefensiveCrouchTypeLowShields : EngineTagDataActorDefensiveCrouchTypeEnum 
---@class EngineTagDataActorDefensiveCrouchTypeHideBehindShield : EngineTagDataActorDefensiveCrouchTypeEnum 
---@class EngineTagDataActorDefensiveCrouchTypeAnyTarget : EngineTagDataActorDefensiveCrouchTypeEnum 
---@class EngineTagDataActorDefensiveCrouchTypeFloodShamble : EngineTagDataActorDefensiveCrouchTypeEnum 

---@alias EngineTagDataActorDefensiveCrouchType 
---| EngineTagDataActorDefensiveCrouchTypeNever
---| EngineTagDataActorDefensiveCrouchTypeDanger
---| EngineTagDataActorDefensiveCrouchTypeLowShields
---| EngineTagDataActorDefensiveCrouchTypeHideBehindShield
---| EngineTagDataActorDefensiveCrouchTypeAnyTarget
---| EngineTagDataActorDefensiveCrouchTypeFloodShamble

---@class EngineTagDataActorDefensiveCrouchTypeTable 
---@field peNever EngineTagDataActorDefensiveCrouchTypeNever
---@field peDanger EngineTagDataActorDefensiveCrouchTypeDanger
---@field peLowShields EngineTagDataActorDefensiveCrouchTypeLowShields
---@field peHideBehindShield EngineTagDataActorDefensiveCrouchTypeHideBehindShield
---@field peAnyTarget EngineTagDataActorDefensiveCrouchTypeAnyTarget
---@field peFloodShamble EngineTagDataActorDefensiveCrouchTypeFloodShamble
Engine.tag.actorDefensiveCrouchType = {} 

---@class MetaEngineTagDataActorFlags 
---@field canSeeInDarkness boolean 
---@field sneakUncoveringTarget boolean 
---@field sneakUncoveringPursuitPosition boolean 
---@field unused boolean 
---@field shootAtTargetSLastLocation boolean 
---@field tryToStayStillWhenCrouched boolean 
---@field crouchWhenNotInCombat boolean 
---@field crouchWhenGuarding boolean 
---@field unused1 boolean 
---@field mustCrouchToShoot boolean 
---@field panicWhenSurprised boolean 
---@field alwaysChargeAtEnemies boolean 
---@field getsInVehiclesWithPlayer boolean 
---@field startFiringBeforeAligned boolean 
---@field standingMustMoveForward boolean 
---@field crouchingMustMoveForward boolean 
---@field defensiveCrouchWhileCharging boolean 
---@field useStalkingBehavior boolean 
---@field stalkingFreezeIfExposed boolean 
---@field alwaysBerserkInAttackingMode boolean 
---@field berserkingUsesPanickedMovement boolean 
---@field flying boolean 
---@field panickedByUnopposableEnemy boolean 
---@field crouchWhenHidingFromUnopposable boolean 
---@field alwaysChargeInAttackingMode boolean 
---@field diveOffLedges boolean 
---@field swarm boolean 
---@field suicidalMeleeAttack boolean 
---@field cannotMoveWhileCrouching boolean 
---@field fixedCrouchFacing boolean 
---@field crouchWhenInLineOfFire boolean 
---@field avoidFriendsLineOfFire boolean 

---@class MetaEngineTagDataActorMoreFlags 
---@field avoidAllEnemyAttackVectors boolean 
---@field mustStandToFire boolean 
---@field mustStopToFire boolean 
---@field disallowVehicleCombat boolean 
---@field pathfindingIgnoresDanger boolean 
---@field panicInGroups boolean 
---@field noCorpseShooting boolean 

---@class MetaEngineTagDataActor 
---@field flags MetaEngineTagDataActorFlags 
---@field moreFlags MetaEngineTagDataActorMoreFlags 
---@field type EngineTagDataActorType 
---@field maxVisionDistance number 
---@field centralVisionAngle MetaEngineAngle 
---@field maxVisionAngle MetaEngineAngle 
---@field peripheralVisionAngle MetaEngineAngle 
---@field peripheralDistance number 
---@field standingGunOffset MetaEngineVector3D 
---@field crouchingGunOffset MetaEngineVector3D 
---@field hearingDistance number 
---@field noticeProjectileChance number 
---@field noticeVehicleChance number 
---@field combatPerceptionTime number 
---@field guardPerceptionTime number 
---@field nonCombatPerceptionTime number 
---@field inverseCombatPerceptionTime number 
---@field inverseGuardPerceptionTime number 
---@field inverseNonCombatPerceptionTime number 
---@field diveIntoCoverChance number 
---@field emergeFromCoverChance number 
---@field diveFromGrenadeChance number 
---@field pathfindingRadius number 
---@field glassIgnoranceChance number 
---@field stationaryMovementDist number 
---@field freeFlyingSidestep number 
---@field beginMovingAngle MetaEngineAngle 
---@field cosineBeginMovingAngle number 
---@field maximumAimingDeviation MetaEngineEuler2D 
---@field maximumLookingDeviation MetaEngineEuler2D 
---@field noncombatLookDeltaL MetaEngineAngle 
---@field noncombatLookDeltaR MetaEngineAngle 
---@field combatLookDeltaL MetaEngineAngle 
---@field combatLookDeltaR MetaEngineAngle 
---@field idleAimingRange MetaEngineEuler2D 
---@field idleLookingRange MetaEngineEuler2D 
---@field eventLookTimeModifier number 
---@field noncombatIdleFacing number 
---@field noncombatIdleAiming number 
---@field noncombatIdleLooking number 
---@field guardIdleFacing number 
---@field guardIdleAiming number 
---@field guardIdleLooking number 
---@field combatIdleFacing number 
---@field combatIdleAiming number 
---@field combatIdleLooking number 
---@field cosineMaximumAimingDeviation MetaEngineEuler2D 
---@field cosineMaximumLookingDeviation MetaEngineEuler2D 
---@field doNotUse MetaEngineTagDependency 
---@field doNotUse1 MetaEngineTagDependency 
---@field unreachableDangerTrigger EngineTagDataActorUnreachableDangerTrigger 
---@field vehicleDangerTrigger EngineTagDataActorUnreachableDangerTrigger 
---@field playerDangerTrigger EngineTagDataActorUnreachableDangerTrigger 
---@field dangerTriggerTime number 
---@field friendsKilledTrigger integer 
---@field friendsRetreatingTrigger integer 
---@field retreatTime number 
---@field coweringTime number 
---@field friendKilledPanicChance number 
---@field leaderType EngineTagDataActorType 
---@field leaderKilledPanicChance number 
---@field panicDamageThreshold number 
---@field surpriseDistance number 
---@field hideBehindCoverTime number 
---@field hideTargetNotVisibleTime number 
---@field hideShieldFraction number 
---@field attackShieldFraction number 
---@field pursueShieldFraction number 
---@field defensiveCrouchType EngineTagDataActorDefensiveCrouchType 
---@field attackingCrouchThreshold number 
---@field defendingCrouchThreshold number 
---@field minStandTime number 
---@field minCrouchTime number 
---@field defendingHideTimeModifier number 
---@field attackingEvasionThreshold number 
---@field defendingEvasionThreshold number 
---@field evasionSeekCoverChance number 
---@field evasionDelayTime number 
---@field maxSeekCoverDistance number 
---@field coverDamageThreshold number 
---@field stalkingDiscoveryTime number 
---@field stalkingMaxDistance number 
---@field stationaryFacingAngle MetaEngineAngle 
---@field changeFacingStandTime number 
---@field uncoverDelayTime number 
---@field targetSearchTime number 
---@field pursuitPositionTime number 
---@field numPositionsCoord integer 
---@field numPositionsNormal integer 
---@field meleeAttackDelay number 
---@field meleeFudgeFactor number 
---@field meleeChargeTime number 
---@field meleeLeapRange number 
---@field meleeLeapVelocity number 
---@field meleeLeapChance number 
---@field meleeLeapBallistic number 
---@field berserkDamageAmount number 
---@field berserkDamageThreshold number 
---@field berserkProximity number 
---@field suicideSensingDist number 
---@field berserkGrenadeChance number 
---@field guardPositionTime number 
---@field combatPositionTime number 
---@field oldPositionAvoidDist number 
---@field friendAvoidDist number 
---@field noncombatIdleSpeechTime number 
---@field combatIdleSpeechTime number 
---@field doNotUse2 MetaEngineTagDependency 


