---@class EngineTagDataMultiplayerInformationSoundEnum : Enum 

---@class EngineTagDataMultiplayerInformationSoundPlayBall : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundGameOver : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundOneMinuteToWin : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSound30SecondsToWin : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundRedTeamMinuteToWin : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundRedTeam30ToWin : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundBlueTeamMinuteToWin : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundBlueTeam30ToWin : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundBlueTeamHasTheFlag : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundBlueTeamFlagReturned : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundBlueTeamScore : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundRedTeamHasTheFlag : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundRedTeamFlagReturned : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundRedTeamScore : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundDoubleKill : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundTripleKill : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundKilltacular : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundRunningRiot : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundKillingSpree : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundOddball : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundRace : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundSlayer : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundCaptureTheFlag : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundWarthog : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundGhost : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundScorpion : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundCountdownTimer : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundTeleporterActivate : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundFlagFailure : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundCountdownForRespawn : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundHillMove : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundPlayerRespawn : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundTeamKingOfTheHill : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundTeamOddball : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundTeamRace : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundTeamSlayer : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundKingOfTheHill : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundBlueTeamCtf : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundRedTeamCtf : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundHillContested : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundHillControlled : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundHillOccupied : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundCountdownTimerEnd : EngineTagDataMultiplayerInformationSoundEnum 
---@class EngineTagDataMultiplayerInformationSoundTing : EngineTagDataMultiplayerInformationSoundEnum 

---@alias EngineTagDataMultiplayerInformationSound 
---| EngineTagDataMultiplayerInformationSoundPlayBall
---| EngineTagDataMultiplayerInformationSoundGameOver
---| EngineTagDataMultiplayerInformationSoundOneMinuteToWin
---| EngineTagDataMultiplayerInformationSound30SecondsToWin
---| EngineTagDataMultiplayerInformationSoundRedTeamMinuteToWin
---| EngineTagDataMultiplayerInformationSoundRedTeam30ToWin
---| EngineTagDataMultiplayerInformationSoundBlueTeamMinuteToWin
---| EngineTagDataMultiplayerInformationSoundBlueTeam30ToWin
---| EngineTagDataMultiplayerInformationSoundBlueTeamHasTheFlag
---| EngineTagDataMultiplayerInformationSoundBlueTeamFlagReturned
---| EngineTagDataMultiplayerInformationSoundBlueTeamScore
---| EngineTagDataMultiplayerInformationSoundRedTeamHasTheFlag
---| EngineTagDataMultiplayerInformationSoundRedTeamFlagReturned
---| EngineTagDataMultiplayerInformationSoundRedTeamScore
---| EngineTagDataMultiplayerInformationSoundDoubleKill
---| EngineTagDataMultiplayerInformationSoundTripleKill
---| EngineTagDataMultiplayerInformationSoundKilltacular
---| EngineTagDataMultiplayerInformationSoundRunningRiot
---| EngineTagDataMultiplayerInformationSoundKillingSpree
---| EngineTagDataMultiplayerInformationSoundOddball
---| EngineTagDataMultiplayerInformationSoundRace
---| EngineTagDataMultiplayerInformationSoundSlayer
---| EngineTagDataMultiplayerInformationSoundCaptureTheFlag
---| EngineTagDataMultiplayerInformationSoundWarthog
---| EngineTagDataMultiplayerInformationSoundGhost
---| EngineTagDataMultiplayerInformationSoundScorpion
---| EngineTagDataMultiplayerInformationSoundCountdownTimer
---| EngineTagDataMultiplayerInformationSoundTeleporterActivate
---| EngineTagDataMultiplayerInformationSoundFlagFailure
---| EngineTagDataMultiplayerInformationSoundCountdownForRespawn
---| EngineTagDataMultiplayerInformationSoundHillMove
---| EngineTagDataMultiplayerInformationSoundPlayerRespawn
---| EngineTagDataMultiplayerInformationSoundTeamKingOfTheHill
---| EngineTagDataMultiplayerInformationSoundTeamOddball
---| EngineTagDataMultiplayerInformationSoundTeamRace
---| EngineTagDataMultiplayerInformationSoundTeamSlayer
---| EngineTagDataMultiplayerInformationSoundKingOfTheHill
---| EngineTagDataMultiplayerInformationSoundBlueTeamCtf
---| EngineTagDataMultiplayerInformationSoundRedTeamCtf
---| EngineTagDataMultiplayerInformationSoundHillContested
---| EngineTagDataMultiplayerInformationSoundHillControlled
---| EngineTagDataMultiplayerInformationSoundHillOccupied
---| EngineTagDataMultiplayerInformationSoundCountdownTimerEnd
---| EngineTagDataMultiplayerInformationSoundTing

---@class EngineTagDataMultiplayerInformationSoundTable 
---@field dPlayBall EngineTagDataMultiplayerInformationSoundPlayBall
---@field dGameOver EngineTagDataMultiplayerInformationSoundGameOver
---@field dOneMinuteToWin EngineTagDataMultiplayerInformationSoundOneMinuteToWin
---@field d30SecondsToWin EngineTagDataMultiplayerInformationSound30SecondsToWin
---@field dRedTeamMinuteToWin EngineTagDataMultiplayerInformationSoundRedTeamMinuteToWin
---@field dRedTeam30ToWin EngineTagDataMultiplayerInformationSoundRedTeam30ToWin
---@field dBlueTeamMinuteToWin EngineTagDataMultiplayerInformationSoundBlueTeamMinuteToWin
---@field dBlueTeam30ToWin EngineTagDataMultiplayerInformationSoundBlueTeam30ToWin
---@field dBlueTeamHasTheFlag EngineTagDataMultiplayerInformationSoundBlueTeamHasTheFlag
---@field dBlueTeamFlagReturned EngineTagDataMultiplayerInformationSoundBlueTeamFlagReturned
---@field dBlueTeamScore EngineTagDataMultiplayerInformationSoundBlueTeamScore
---@field dRedTeamHasTheFlag EngineTagDataMultiplayerInformationSoundRedTeamHasTheFlag
---@field dRedTeamFlagReturned EngineTagDataMultiplayerInformationSoundRedTeamFlagReturned
---@field dRedTeamScore EngineTagDataMultiplayerInformationSoundRedTeamScore
---@field dDoubleKill EngineTagDataMultiplayerInformationSoundDoubleKill
---@field dTripleKill EngineTagDataMultiplayerInformationSoundTripleKill
---@field dKilltacular EngineTagDataMultiplayerInformationSoundKilltacular
---@field dRunningRiot EngineTagDataMultiplayerInformationSoundRunningRiot
---@field dKillingSpree EngineTagDataMultiplayerInformationSoundKillingSpree
---@field dOddball EngineTagDataMultiplayerInformationSoundOddball
---@field dRace EngineTagDataMultiplayerInformationSoundRace
---@field dSlayer EngineTagDataMultiplayerInformationSoundSlayer
---@field dCaptureTheFlag EngineTagDataMultiplayerInformationSoundCaptureTheFlag
---@field dWarthog EngineTagDataMultiplayerInformationSoundWarthog
---@field dGhost EngineTagDataMultiplayerInformationSoundGhost
---@field dScorpion EngineTagDataMultiplayerInformationSoundScorpion
---@field dCountdownTimer EngineTagDataMultiplayerInformationSoundCountdownTimer
---@field dTeleporterActivate EngineTagDataMultiplayerInformationSoundTeleporterActivate
---@field dFlagFailure EngineTagDataMultiplayerInformationSoundFlagFailure
---@field dCountdownForRespawn EngineTagDataMultiplayerInformationSoundCountdownForRespawn
---@field dHillMove EngineTagDataMultiplayerInformationSoundHillMove
---@field dPlayerRespawn EngineTagDataMultiplayerInformationSoundPlayerRespawn
---@field dTeamKingOfTheHill EngineTagDataMultiplayerInformationSoundTeamKingOfTheHill
---@field dTeamOddball EngineTagDataMultiplayerInformationSoundTeamOddball
---@field dTeamRace EngineTagDataMultiplayerInformationSoundTeamRace
---@field dTeamSlayer EngineTagDataMultiplayerInformationSoundTeamSlayer
---@field dKingOfTheHill EngineTagDataMultiplayerInformationSoundKingOfTheHill
---@field dBlueTeamCtf EngineTagDataMultiplayerInformationSoundBlueTeamCtf
---@field dRedTeamCtf EngineTagDataMultiplayerInformationSoundRedTeamCtf
---@field dHillContested EngineTagDataMultiplayerInformationSoundHillContested
---@field dHillControlled EngineTagDataMultiplayerInformationSoundHillControlled
---@field dHillOccupied EngineTagDataMultiplayerInformationSoundHillOccupied
---@field dCountdownTimerEnd EngineTagDataMultiplayerInformationSoundCountdownTimerEnd
---@field dTing EngineTagDataMultiplayerInformationSoundTing
Engine.tag.multiplayerInformationSound = {} 

---@class MetaEngineTagDataGlobalsRasterizerDataFlags 
---@field tintEdgeDensity boolean 

---@class MetaEngineTagDataGlobalsBreakableSurfaceParticleEffectFlags 
---@field interpolateColorInHsv boolean 
---@field moreColors boolean 

---@class MetaEngineTagDataGlobalsSound 
---@field sound MetaEngineTagDependency 

---@class MetaEngineTagDataGlobalsCamera 
---@field defaultUnitCameraTrack MetaEngineTagDependency 

---@class MetaEngineTagDataGlobalsLookFunction 
---@field scale number 

---@class MetaEngineTagDataGlobalsPlayerControl 
---@field magnetismFriction number 
---@field magnetismAdhesion number 
---@field inconsequentialTargetScale number 
---@field lookAccelerationTime number 
---@field lookAccelerationScale number 
---@field lookPegThreshold number 
---@field lookDefaultPitchRate number 
---@field lookDefaultYawRate number 
---@field lookAutolevellingScale number 
---@field minimumWeaponSwapTicks integer 
---@field minimumAutolevellingTicks integer 
---@field minimumAngleForVehicleFlipping MetaEngineAngle 
---@field lookFunction TagBlock<MetaEngineTagDataGlobalsLookFunction> 

---@class MetaEngineTagDataGlobalsDifficulty 
---@field easyEnemyDamage number 
---@field normalEnemyDamage number 
---@field hardEnemyDamage number 
---@field impossEnemyDamage number 
---@field easyEnemyVitality number 
---@field normalEnemyVitality number 
---@field hardEnemyVitality number 
---@field impossEnemyVitality number 
---@field easyEnemyShield number 
---@field normalEnemyShield number 
---@field hardEnemyShield number 
---@field impossEnemyShield number 
---@field easyEnemyRecharge number 
---@field normalEnemyRecharge number 
---@field hardEnemyRecharge number 
---@field impossEnemyRecharge number 
---@field easyFriendDamage number 
---@field normalFriendDamage number 
---@field hardFriendDamage number 
---@field impossFriendDamage number 
---@field easyFriendVitality number 
---@field normalFriendVitality number 
---@field hardFriendVitality number 
---@field impossFriendVitality number 
---@field easyFriendShield number 
---@field normalFriendShield number 
---@field hardFriendShield number 
---@field impossFriendShield number 
---@field easyFriendRecharge number 
---@field normalFriendRecharge number 
---@field hardFriendRecharge number 
---@field impossFriendRecharge number 
---@field easyInfectionForms number 
---@field normalInfectionForms number 
---@field hardInfectionForms number 
---@field impossInfectionForms number 
---@field easyRateOfFire number 
---@field normalRateOfFire number 
---@field hardRateOfFire number 
---@field impossRateOfFire number 
---@field easyProjectileError number 
---@field normalProjectileError number 
---@field hardProjectileError number 
---@field impossProjectileError number 
---@field easyBurstError number 
---@field normalBurstError number 
---@field hardBurstError number 
---@field impossBurstError number 
---@field easyNewTargetDelay number 
---@field normalNewTargetDelay number 
---@field hardNewTargetDelay number 
---@field impossNewTargetDelay number 
---@field easyBurstSeparation number 
---@field normalBurstSeparation number 
---@field hardBurstSeparation number 
---@field impossBurstSeparation number 
---@field easyTargetTracking number 
---@field normalTargetTracking number 
---@field hardTargetTracking number 
---@field impossTargetTracking number 
---@field easyTargetLeading number 
---@field normalTargetLeading number 
---@field hardTargetLeading number 
---@field impossTargetLeading number 
---@field easyOverchargeChance number 
---@field normalOverchargeChance number 
---@field hardOverchargeChance number 
---@field impossOverchargeChance number 
---@field easySpecialFireDelay number 
---@field normalSpecialFireDelay number 
---@field hardSpecialFireDelay number 
---@field impossSpecialFireDelay number 
---@field easyGuidanceVsPlayer number 
---@field normalGuidanceVsPlayer number 
---@field hardGuidanceVsPlayer number 
---@field impossGuidanceVsPlayer number 
---@field easyMeleeDelayBase number 
---@field normalMeleeDelayBase number 
---@field hardMeleeDelayBase number 
---@field impossMeleeDelayBase number 
---@field easyMeleeDelayScale number 
---@field normalMeleeDelayScale number 
---@field hardMeleeDelayScale number 
---@field impossMeleeDelayScale number 
---@field easyGrenadeChanceScale number 
---@field normalGrenadeChanceScale number 
---@field hardGrenadeChanceScale number 
---@field impossGrenadeChanceScale number 
---@field easyGrenadeTimerScale number 
---@field normalGrenadeTimerScale number 
---@field hardGrenadeTimerScale number 
---@field impossGrenadeTimerScale number 
---@field easyMajorUpgrade number 
---@field normalMajorUpgrade number 
---@field hardMajorUpgrade number 
---@field impossMajorUpgrade number 
---@field easyMajorUpgrade1 number 
---@field normalMajorUpgrade1 number 
---@field hardMajorUpgrade1 number 
---@field impossMajorUpgrade1 number 
---@field easyMajorUpgrade2 number 
---@field normalMajorUpgrade2 number 
---@field hardMajorUpgrade2 number 
---@field impossMajorUpgrade2 number 

---@class MetaEngineTagDataGlobalsGrenade 
---@field maximumCount integer 
---@field mpSpawnDefault integer 
---@field throwingEffect MetaEngineTagDependency 
---@field hudInterface MetaEngineTagDependency 
---@field equipment MetaEngineTagDependency 
---@field projectile MetaEngineTagDependency 

---@class MetaEngineTagDataGlobalsRasterizerData 
---@field distanceAttenuation MetaEngineTagDependency 
---@field vectorNormalization MetaEngineTagDependency 
---@field atmosphericFogDensity MetaEngineTagDependency 
---@field planarFogDensity MetaEngineTagDependency 
---@field linearCornerFade MetaEngineTagDependency 
---@field activeCamouflageDistortion MetaEngineTagDependency 
---@field glow MetaEngineTagDependency 
---@field default2d MetaEngineTagDependency 
---@field default3d MetaEngineTagDependency 
---@field defaultCubeMap MetaEngineTagDependency 
---@field test0 MetaEngineTagDependency 
---@field test1 MetaEngineTagDependency 
---@field test2 MetaEngineTagDependency 
---@field test3 MetaEngineTagDependency 
---@field videoScanlineMap MetaEngineTagDependency 
---@field videoNoiseMap MetaEngineTagDependency 
---@field flags MetaEngineTagDataGlobalsRasterizerDataFlags 
---@field refractionAmount number 
---@field distanceFalloff number 
---@field tintColor MetaEngineColorRGB 
---@field hyperStealthRefraction number 
---@field hyperStealthDistanceFalloff number 
---@field hyperStealthTintColor MetaEngineColorRGB 
---@field distanceAttenuation2d MetaEngineTagDependency 

---@class MetaEngineTagDataGlobalsInterfaceBitmaps 
---@field fontSystem MetaEngineTagDependency 
---@field fontTerminal MetaEngineTagDependency 
---@field screenColorTable MetaEngineTagDependency 
---@field hudColorTable MetaEngineTagDependency 
---@field editorColorTable MetaEngineTagDependency 
---@field dialogColorTable MetaEngineTagDependency 
---@field hudGlobals MetaEngineTagDependency 
---@field motionSensorSweepBitmap MetaEngineTagDependency 
---@field motionSensorSweepBitmapMask MetaEngineTagDependency 
---@field multiplayerHudBitmap MetaEngineTagDependency 
---@field localization MetaEngineTagDependency 
---@field hudDigitsDefinition MetaEngineTagDependency 
---@field motionSensorBlipBitmap MetaEngineTagDependency 
---@field interfaceGooMap1 MetaEngineTagDependency 
---@field interfaceGooMap2 MetaEngineTagDependency 
---@field interfaceGooMap3 MetaEngineTagDependency 

---@class MetaEngineTagDataGlobalsWeapon 
---@field weapon MetaEngineTagDependency 

---@class MetaEngineTagDataGlobalsCheatPowerup 
---@field powerup MetaEngineTagDependency 

---@class MetaEngineTagDataGlobalsVehicle 
---@field vehicle MetaEngineTagDependency 

---@class MetaEngineTagDataGlobalsMultiplayerInformation 
---@field flag MetaEngineTagDependency 
---@field unit MetaEngineTagDependency 
---@field vehicles TagBlock<MetaEngineTagDataGlobalsVehicle> 
---@field hillShader MetaEngineTagDependency 
---@field flagShader MetaEngineTagDependency 
---@field ball MetaEngineTagDependency 
---@field sounds TagBlock<MetaEngineTagDataGlobalsSound> 

---@class MetaEngineTagDataGlobalsPlayerInformation 
---@field unit MetaEngineTagDependency 
---@field walkingSpeed number 
---@field doubleSpeedMultiplier number 
---@field runForward number 
---@field runBackward number 
---@field runSideways number 
---@field runAcceleration number 
---@field sneakForward number 
---@field sneakBackward number 
---@field sneakSideways number 
---@field sneakAcceleration number 
---@field airborneAcceleration number 
---@field speedMultiplier number 
---@field grenadeOrigin MetaEnginePoint3D 
---@field stunMovementPenalty number 
---@field stunTurningPenalty number 
---@field stunJumpingPenalty number 
---@field minimumStunTime number 
---@field maximumStunTime number 
---@field firstPersonIdleTime number 
---@field firstPersonSkipFraction number 
---@field coopRespawnEffect MetaEngineTagDependency 

---@class MetaEngineTagDataGlobalsFirstPersonInterface 
---@field firstPersonHands MetaEngineTagDependency 
---@field baseBitmap MetaEngineTagDependency 
---@field shieldMeter MetaEngineTagDependency 
---@field shieldMeterOrigin MetaEnginePoint2DInt 
---@field bodyMeter MetaEngineTagDependency 
---@field bodyMeterOrigin MetaEnginePoint2DInt 
---@field nightVisionOnEffect MetaEngineTagDependency 
---@field nightVisionOffEffect MetaEngineTagDependency 

---@class MetaEngineTagDataGlobalsFallingDamage 
---@field harmfulFallingDistance number 
---@field fallingDamage MetaEngineTagDependency 
---@field maximumFallingDistance number 
---@field distanceDamage MetaEngineTagDependency 
---@field vehicleEnvironmentCollisionDamage MetaEngineTagDependency 
---@field vehicleKilledUnitDamage MetaEngineTagDependency 
---@field vehicleCollisionDamage MetaEngineTagDependency 
---@field flamingDeathDamage MetaEngineTagDependency 
---@field maximumFallingVelocity number 
---@field harmfulFallingVelocity number 

---@class MetaEngineTagDataGlobalsBreakableSurfaceParticleEffect 
---@field particleType MetaEngineTagDependency 
---@field flags MetaEngineTagDataGlobalsBreakableSurfaceParticleEffectFlags 
---@field density number 
---@field velocityScale number 
---@field angularVelocity number 
---@field radius number 
---@field tintLowerBound MetaEngineColorARGB 
---@field tintUpperBound MetaEngineColorARGB 

---@class MetaEngineTagDataGlobalsMaterial 
---@field groundFrictionScale number 
---@field groundFrictionNormalK1Scale number 
---@field groundFrictionNormalK0Scale number 
---@field groundDepthScale number 
---@field groundDampFractionScale number 
---@field maximumVitality number 
---@field effect MetaEngineTagDependency 
---@field sound MetaEngineTagDependency 
---@field particleEffects TagBlock<MetaEngineTagDataGlobalsBreakableSurfaceParticleEffect> 
---@field meleeHitSound MetaEngineTagDependency 

---@class MetaEngineTagDataGlobalsPlaylistMember 
---@field mapName MetaEngineTagString 
---@field gameVariant MetaEngineTagString 
---@field minimumExperience integer 
---@field maximumExperience integer 
---@field minimumPlayerCount integer 
---@field maximumPlayerCount integer 
---@field rating integer 

---@class MetaEngineTagDataGlobals 
---@field sounds TagBlock<MetaEngineTagDataGlobalsSound> 
---@field camera TagBlock<MetaEngineTagDataGlobalsCamera> 
---@field playerControl TagBlock<MetaEngineTagDataGlobalsPlayerControl> 
---@field difficulty TagBlock<MetaEngineTagDataGlobalsDifficulty> 
---@field grenades TagBlock<MetaEngineTagDataGlobalsGrenade> 
---@field rasterizerData TagBlock<MetaEngineTagDataGlobalsRasterizerData> 
---@field interfaceBitmaps TagBlock<MetaEngineTagDataGlobalsInterfaceBitmaps> 
---@field weaponList TagBlock<MetaEngineTagDataGlobalsWeapon> 
---@field cheatPowerups TagBlock<MetaEngineTagDataGlobalsCheatPowerup> 
---@field multiplayerInformation TagBlock<MetaEngineTagDataGlobalsMultiplayerInformation> 
---@field playerInformation TagBlock<MetaEngineTagDataGlobalsPlayerInformation> 
---@field firstPersonInterface TagBlock<MetaEngineTagDataGlobalsFirstPersonInterface> 
---@field fallingDamage TagBlock<MetaEngineTagDataGlobalsFallingDamage> 
---@field materials TagBlock<MetaEngineTagDataGlobalsMaterial> 
---@field playlistMembers TagBlock<MetaEngineTagDataGlobalsPlaylistMember> 


